Traceback (most recent call last):
  File "c:\users\hehez\onedrive\github\pyppg-handbook\venv\lib\site-packages\jupyter_cache\executors\utils.py", line 51, in single_nb_execution
    executenb(
  File "c:\users\hehez\onedrive\github\pyppg-handbook\venv\lib\site-packages\nbclient\client.py", line 1204, in execute
    return NotebookClient(nb=nb, resources=resources, km=km, **kwargs).execute()
  File "c:\users\hehez\onedrive\github\pyppg-handbook\venv\lib\site-packages\nbclient\util.py", line 84, in wrapped
    return just_run(coro(*args, **kwargs))
  File "c:\users\hehez\onedrive\github\pyppg-handbook\venv\lib\site-packages\nbclient\util.py", line 62, in just_run
    return loop.run_until_complete(coro)
  File "C:\Program Files\WindowsApps\PythonSoftwareFoundation.Python.3.8_3.8.2800.0_x64__qbz5n2kfra8p0\lib\asyncio\base_events.py", line 616, in run_until_complete
    return future.result()
  File "c:\users\hehez\onedrive\github\pyppg-handbook\venv\lib\site-packages\nbclient\client.py", line 663, in async_execute
    await self.async_execute_cell(
  File "c:\users\hehez\onedrive\github\pyppg-handbook\venv\lib\site-packages\nbclient\client.py", line 965, in async_execute_cell
    await self._check_raise_for_error(cell, cell_index, exec_reply)
  File "c:\users\hehez\onedrive\github\pyppg-handbook\venv\lib\site-packages\nbclient\client.py", line 862, in _check_raise_for_error
    raise CellExecutionError.from_cell_and_msg(cell, exec_reply_content)
nbclient.exceptions.CellExecutionError: An error occurred while executing the following cell:
------------------
from hapy.spt_process import spt_process as sp
------------------

[1;31m---------------------------------------------------------------------------[0m
[1;31mModuleNotFoundError[0m                       Traceback (most recent call last)
Cell [1;32mIn[1], line 1[0m
[1;32m----> 1[0m [38;5;28;01mfrom[39;00m [38;5;21;01mhapy[39;00m[38;5;21;01m.[39;00m[38;5;21;01mspt_process[39;00m [38;5;28;01mimport[39;00m spt_process [38;5;28;01mas[39;00m sp

[1;31mModuleNotFoundError[0m: No module named 'hapy'
ModuleNotFoundError: No module named 'hapy'

